name: Build and Package React App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source project
      uses: actions/checkout@v4
      
    - name: Checkout electron packaging project
      uses: actions/checkout@v4
      with:
        repository: noaamaman325158/hooliLaunchPackage  
        token: ${{ secrets.PAT_TOKEN }}
        path: electron-project

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: './ClientSide/client/package-lock.json'

    - name: Build React App
      working-directory: ./ClientSide/client
      run: |
        npm ci
        CI=false npm run build
        
    - name: Clear and Create electron build directory
      run: |
        rm -rf electron-project/build
        mkdir -p electron-project/build
      
    - name: Copy build files to electron project
      run: |
        cp -r ClientSide/client/build/* electron-project/build/

    - name: Install electron-builder dependencies
      working-directory: ./electron-project
      run: |
        npm ci

    - name: Run electron-builder
      working-directory: ./electron-project
      run: |
        npx electron-builder --win --x64
        
    - name: Commit and push to electron project
      working-directory: ./electron-project
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add build dist
        git commit -m "Update build files and electron package" || echo "No changes to commit"
        git push
